apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
        - name: hw-app
          image: ${ecr_domain}:${image_tag}
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service