apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
        - name: hw-app
          image: 134317053521.dkr.ecr.ap-southeast-1.amazonaws.com/hw-ecr:12bf0ba600e84449bb116cefeba64e05c7e3a91c
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service